### ISSUE TITLE
Add more benchmarks

### ISSUE THREAD

**Issue by Bykiev** [AntonovAnton/math.evaluation#43]
The project has a benchmark where Math.Evaluator is compared with NCalc library. Can you please add more tests, for example, with [lambda compilation](https://ncalc.github.io/ncalc/articles/lambda_compilation.html)? 

Can you please also update BenchmarkDotNet to the latest version?

**Comment by AntonovAnton** [comment]
Hi! About BenchmarkDotNet 14 it doesn't support .NET 6 so until I stay with .NET 6 as a target platform I will use BenchmarkDotNet 13.
